GET http://localhost:9090/currencies

###
GET http://localhost:9090/currency/EUR

###

GET http://localhost:9090/currency/EEE
###

GET http://localhost:9090/currency
###

POST http://localhost:9090/currencies
Content-Type: application/x-www-form-urlencoded

name = Tenge &
code = KZT &
sign = ₸

###

POST http://localhost:9090/currencies
Content-Type: application/x-www-form-urlencoded

name = Ruble &
code = RUB &
sign = ₽
###
POST http://localhost:9090/currencies
Content-Type: application/x-www-form-urlencoded

name = Thai baht &
code = THB
###

POST http://localhost:9090/currencies
Content-Type: application/x-www-form-urlencoded

name = Australian dollar &
code = AUD &
sign = A$
###